### ISSUE TITLE
Deprecation notice: psr-4 autoloading

### ISSUE THREAD

**Issue by WimWidgets** [czim/laravel-filter#12]
`Deprecation Notice: Class Czim\Filter\ParameterFilters\IsEmpty located in ./vendor/czim/laravel-filter/src/ParameterFilters/Empty.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0.`

**Comment by czim** [comment]
Good catch, that file is clearly misnamed. Fixed in `2.0.2`.
