### ISSUE TITLE
Laravel 8 upgrade support 

### ISSUE THREAD

**Issue by kenean-50** [czim/laravel-filter#13]
am trying to upgrade my project to Laravel 8 and this package is not compatible.
Is there a possibility of an upgrade?

**Comment by czim** [comment]
Yes I do intend to upgrade most of my packages where required. If you're in a hurry, I recommend making a PR for this. The code is quite ancient, but doesn't rely on any real framework magic, so it should be a minor change.

**Comment by czim** [comment]
I've released 3.0.0 with Laravel 8 support. Note that the code was cleaned up and there are some breaking changes. See the change log for more information. Upgrading shouldn't be difficult, let me know if you run into any issues.
