### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by robertheydenrych** [czim/laravel-filter#15]
Are there any plans to update this package to support the recently released Laravel 10?

**Comment by czim** [comment]
Unless there are breaking changes in Laravel 10 that make the package pointless, it will support 10, yes. No specific plans or time schedule though.

**Comment by robertheydenrych** [comment]
Thanks for the update, I'm busy upgrading a project to Laravel 10 at the moment that uses this package. I'll keep checking back for future updates.
