### ISSUE TITLE
CountableFilters data array access

### ISSUE THREAD

**Issue by a-komarev** [czim/laravel-filter#4]
If filter countable has multi dimensional array in it:
```php
$filterCounters->get('age_groups');

// OUTPUT
[
    '14-25' => 1,
    '26-30' => 5,
    '31-40' => 14,
    '41-50' => 10,
]
```

It could be accessed like: `$filterCounters->get('age_groups')['14-25'];`

But if there is no such key in array - template will return an exception, and there is a need to `isset()` checks in template and they started to smell a lot.

It would be great to have laravel way syntax for the array data access:

```php
$filterCounters->get('age_groups.14-25');
```

Or am I doing it wrong and each age range should be fetched separately? If so, there would be much more than 500 counters in current app :'(

Output result should be like this:

![selection_134](https://cloud.githubusercontent.com/assets/1849174/15627936/c9595e72-2504-11e6-812c-d70f8f1bea16.png)

**Comment by czim** [comment]
`CountableResults` is a [Laravel `Collection`](https://laravel.com/docs/5.2/eloquent-collections), so you can use any of its typical access methods to get details. For nested data, it depends on how you handle the Countable implementation. 

The provided `SimpleDistinctValue` counting strategy returns a QueryBuilder `lists()` return value, which is a simple array in Laravel 5.1.

One solution might be to perform a `toArray()` on the `CountableResults`, so you can use `array_get()` and other dot notation methods. Another is to roll your own counting strategies, which return collections or data objects that may help you to return default data without requiring isset() checks.
