### ISSUE TITLE
Dependent strategies

### ISSUE THREAD

**Issue by a-komarev** [czim/laravel-filter#6]
I'm making search form with 2 dependent inputs:
- `city`
- `distance`

If user choose `city` and `distance == null` - then search results will include only entities within the `city`. If user choose `city` + `distance` search should ignore `city` strategy and execute only `distance` strategy with city center coordinates as a start point for distance calculations.

I've tried to get `$this->data->attributes` in `city` strategy to check if distance value is not empty and go to next strategy, but it's protected property.

Am I doing it wrong and maybe this could be solved by rules?

**Comment by a-komarev** [comment]
@czim I found that `FilterDataInterface` missing `getAttributes` method. Gonna make PR for it.

**Comment by czim** [comment]
You can call `parameterValue($key)` on the Filter instance to check which value is set. So you can call that to check on another parameter's value while parsing the application of some other value.

It's a public method, so you can even call it from strategies.

Alternatively, you can create settings (which, in your example is obviously not the right approach) and check them using `setting($key)`.

**Comment by a-komarev** [comment]
Thank you. `parameterValue` is enough for my case.
